---
- name: Install 'bind9' Package
  apt:
    name: bind9
    update_cache: yes
    state: present

- name: Create '/etc/bind/zones' Directory
  file:
    path: /etc/bind/zones
    state: directory
    owner: bind
    group: bind
    mode: '0744'
  notify: "Restart Bind9 Service"

- name: Copy '/etc/bind/named.conf' File
  copy:
    src: named.conf
    dest: /etc/bind/named.conf
    owner: root
    group: bind
    mode: "0644"
  notify: "Restart Bind9 Service"

- name: Copy '/etc/bind/named.conf.default-zones' File
  copy:
    src: named.conf.default-zones
    dest: /etc/bind/named.conf.default-zones
    owner: root
    group: bind
    mode: "0644"
  notify: "Restart Bind9 Service"

- name: Copy '/etc/bind/named.conf.local' File
  copy:
    src: named.conf.local
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: "0644"
  notify: "Restart Bind9 Service"

- name: Copy '/etc/bind/named.conf.options' File
  copy:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: "0644"
  notify: "Restart Bind9 Service"

- name: Copy '/etc/bind/named.conf.options' File
  copy:
    src: named.conf.options
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: "0644"
  notify: "Restart Bind9 Service"

- name: Deploy '/etc/bind/zones/10.10.in-addr.arpa' Template
  template:
    src: 10.10.in-addr.arpa.j2
    dest: /etc/bind/zones/10.10.in-addr.arpa
    owner: bind
    group: bind
    mode: "0644"
  notify: "Restart Bind9 Service"

- name: Deploy '/etc/bind/zones/db.localdomain' Template
  template:
    src: db.localdomain.j2
    dest: /etc/bind/zones/db.localdomain
    owner: bind
    group: bind
    mode: "0644"
  notify: "Restart Bind9 Service"