---
- name: Restart SSH Service
  service:
    name: ssh
    state: restarted
  listen: "Restart SSH Service"

- name: Restart NTP Service
  service:
    name: ntp
    state: started
  listen: "Restart Time Service"

- name: Restart Networking Service
  service:
    name: networking
    state: restarted
  listen: "Start Network Service"